Modified author contact information
alibabacloud-automation/terraform-alicloud-slb-rule pull request #3
Opened 2021-09-16 08:35 UTC by china-1947

Modified author contact information

2021-12-23 06:28 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +  description = "Port used by the Server Load Balancer instance backend. Valid value range: [1-65535]."
type

2021-12-23 06:28 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +variable "frontend_port" {
type

2021-12-23 06:28 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +variable "bandwidth" {
type

2021-12-23 06:28 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +variable "bandwidth" {
整体加一下

2021-12-23 06:28 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +unhealthy_threshold  = 3
跟variables.tf定义的值没有变化

2021-12-23 06:28 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +cookie_timeout     = 100
没有用到

2021-12-24 10:43 UTC, xiaozhu36 requested changes

2021-12-24 10:43 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  enable_details = true
enable_details = true
 这个不需要设置

2021-12-28 03:17 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +frontend_port = 30
health_check_connect_port

2021-12-28 03:17 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +frontend_port = 30
bandwidth

2022-01-05 02:36 UTC, merged